---
- name: Create a new organization
  tower_organization:
    name: "{{ organization_name }}"    
    state: present
    tower_username: admin
    tower_password: password

- name: Create an Inventory
  tower_inventory:
    name: "{{ inventory_name }}"  
    organization: "{{ organization_name }}"
    state: present  
    tower_username: admin
    tower_password: password

- name: Create a Hosts
  tower_host:
    name: "{{ item }}"
    inventory: "{{ inventory_name }}"
    state: present
    tower_username: admin
    tower_password: password
  with_items: "{{ host_name }}"    
 
- name: Create a Team
  tower_team:
    name: "{{ team_name }}"   
    organization: "{{ organization_name }}"
    state: present
    validate_certs: false
    tower_username: admin
    tower_password: password

- name: Add Tower users
  tower_user:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email }}"
    first_name: "{{ item.first_name }}"
    last_name: "{{ item.last_name }}"
    state: present
    tower_username: admin
    tower_password: password
  with_items: "{{ user_details }}"

- name: Create a valid SCM credential from a private_key file
  tower_credential:
    name: git-key
    organization: "{{ organization_name }}"
    state: present
    credential_type: Source Control
    tower_username: admin
    tower_password: password
    inputs:      
      ssh_key_data: "{{ lookup('file', '/home/ec2-user/.ssh/gitawx') }}"

  

  
